[package]
name = "rquickjs_test"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = { git = "https://github.com/DelSkayn/rquickjs.git", features = ["full-async"] }
tokio = { version = "1.43.0", features = ["macros", "rt"] }
